services:
  app:
    build: .
    command: /bin/bash
    volumes:
      - type: bind
        source: ~/.ssh/
        target: /root/.ssh/
        read_only: false
      - type: bind
        source: ~/.kube/
        target: /root/.kube/
        read_only: false
